# Generated by Django 5.1.4 on 2024-12-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_description',
            field=models.CharField(default='Stunning artwork made by ME', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='art_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
