# Generated by Django 5.1.4 on 2025-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_artwork_art_description_artwork_art_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='number',
            field=models.FloatField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
