# Generated by Django 5.1.4 on 2025-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_artwork_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
