# Generated by Django 5.1.4 on 2025-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_artwork_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('bid', models.FloatField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='number',
        ),
    ]
